sonar.host.url=http://localhost:9000
sonar.projectKey=management-frontend
sonar.projectName=School System Frontend
sonar.projectVersion=0.1.0
sonar.sources=src
sonar.tests=src/__tests__
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=dist/**, node_modules/**, coverage/**, **/*.test.js, **/*.spec.js, **/*.test.jsx, **/*.spec.jsx, .vite/**, **/.scannerwork/**, src/test/**