sonar.host.url=http://localhost:9000
sonar.projectKey=management-frontend
sonar.projectName=School System Frontend
sonar.projectVersion=0.1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=dist/**, node_modules/**, **/*.test.js, **/*.spec.js