"""user auth_version

Revision ID: 6ba014ee526e
Revises: c4b1a9f2e8d3
Create Date: 2026-09-10 17:46:57.389621

"""

import sqlalchemy as sa
from alembic import op

revision = "6ba014ee526e"
down_revision = "c4b1a9f2e8d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "auth_version", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_version")
    # ### end Alembic commands ###